"""add webhook_secret to merchants

Revision ID: 00fabeae3902
Revises: 6bede1a0a71e
Create Date: 2026-08-16 19:47:00.328833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fabeae3902'
down_revision: Union[str, None] = '6bede1a0a71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('webhook_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'webhook_secret')
    # ### end Alembic commands ###