"""add settlements table and payment settlement_id

Revision ID: 5aa16530b028
Revises: 00fabeae3902
Create Date: 2026-08-18 11:44:38.783387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aa16530b028'
down_revision: Union[str, None] = '00fabeae3902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='settlementstatus'), nullable=False),
    sa.Column('payment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('payments', sa.Column('settlement_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'payments', 'settlements', ['settlement_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'settled_at')
    op.drop_column('payments', 'settlement_id')
    op.drop_table('settlements')
    # ### end Alembic commands ###