"""add reason column to refunds

Revision ID: 6bede1a0a71e
Revises: efd31d330bf2
Create Date: 2026-08-14 22:55:23.595977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bede1a0a71e'
down_revision: Union[str, None] = 'efd31d330bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ledger_entries', sa.Column('account', sa.String(), nullable=False))
    op.add_column('refunds', sa.Column('reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refunds', 'reason')
    op.drop_column('ledger_entries', 'account')
    # ### end Alembic commands ###