"""add account column to ledger_entries

Revision ID: efd31d330bf2
Revises: 472fe4dfa6ce
Create Date: 2026-08-14 22:39:22.923099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd31d330bf2'
down_revision: Union[str, None] = '472fe4dfa6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###